package persistence.sql.ddl.assembler;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import persistence.TestUtils;
import persistence.entity.Order;
import persistence.entity.OrderItem;

class DataDefinitionLanguageAssemblerTest {
    @Test
    @DisplayName("Order create table ddl 생성 테스트")
    void test_create_order_table() {
        // given
        DataDefinitionLanguageAssembler dataDefinitionLanguageAssembler = TestUtils.createDataDefinitionLanguageAssembler();

        // when
        String sql = dataDefinitionLanguageAssembler.assembleCreateTableQuery(Order.class);

        // then
        String expected = "create table orders(\n"
            + "id bigint generated by default as identity,\n"
            + "orderNumber varchar(300)\n"
            + ");";
        assertThat(sql).isEqualTo(expected);
    }

    @Test
    @DisplayName("Order drop table ddl 삭제 테스트")
    void test_drop_order_table() {
        // given
        DataDefinitionLanguageAssembler dataDefinitionLanguageAssembler = TestUtils.createDataDefinitionLanguageAssembler();

        // when
        String sql = dataDefinitionLanguageAssembler.assembleDropTableQuery(Order.class);

        // then
        String expected = "drop table orders if exists;";
        assertThat(sql).isEqualTo(expected);
    }

    @Test
    @DisplayName("OrderItem create table ddl 생성 테스트")
    void test_create_orderItem_table() {
        // given
        DataDefinitionLanguageAssembler dataDefinitionLanguageAssembler = TestUtils.createDataDefinitionLanguageAssembler();

        // when
        String sql = dataDefinitionLanguageAssembler.assembleCreateTableQuery(OrderItem.class);

        // then
        String expected = "create table order_items(\n"
            + "id bigint generated by default as identity,\n"
            + "product varchar(300),\n"
            + "quantity int\n"
            + ");";
        assertThat(sql).isEqualTo(expected);
    }

    @Test
    @DisplayName("OrderItem drop table ddl 삭제 테스트")
    void test_drop_orderItem_table() {
        // given
        DataDefinitionLanguageAssembler dataDefinitionLanguageAssembler = TestUtils.createDataDefinitionLanguageAssembler();

        // when
        String sql = dataDefinitionLanguageAssembler.assembleDropTableQuery(OrderItem.class);

        // then
        String expected = "drop table order_items if exists;";
        assertThat(sql).isEqualTo(expected);
    }
}
